/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/conversas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversas */
        get: operations["conversas_admin_conversas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/conversas/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversa */
        get: operations["conversa_admin_conversas__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eventos Do Painel
         * @description O barramento, como SSE. É o que faz o painel dispensar polling.
         *
         *     A autenticação acontece **antes** de abrir o stream, na função da rota, e
         *     não dentro do gerador: um 401 emitido de dentro do stream já teria mandado
         *     200 na linha de status, e o cliente aprenderia a tratar não-autorizado como
         *     sucesso.
         */
        get: operations["eventos_do_painel_admin_eventos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metricas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metricas */
        get: operations["metricas_admin_metricas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista De Pedidos */
        get: operations["lista_de_pedidos_admin_pedidos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/pedidos/{pedido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pedido No Painel */
        get: operations["pedido_no_painel_admin_pedidos__pedido_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prompts
         * @description Os prompts vigentes, **em leitura**. Não existe rota que os escreva.
         *
         *     `editavel` é um literal `False` no contrato, e não um booleano calculado:
         *     o cliente TypeScript passa a ter o tipo `false`, e um botão de salvar nem
         *     chega a compilar. É a forma mais barata de manter a decisão do ADR-015
         *     depois que alguém esquecer por que ela existe.
         */
        get: operations["prompts_admin_prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Config */
        get: operations["read_config_config_get"];
        /** Write Config */
        put: operations["write_config_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eventos/sessao/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eventos Da Sessao
         * @description O push para o chat do cliente — e o que fecha a ressalva R-2 da S-05.
         *
         *     O RF-3.6 diz que o cliente **recebe** a confirmação da nota. Até aqui ele
         *     perguntava e o agente consultava (S-05, D-8), e a verificação independente
         *     registrou o estreitamento com a observação de que *"a S-07 deveria fechar de
         *     verdade"*. Com esta rota, aprovar no painel faz o cartão da NF aparecer no
         *     widget sem que ninguém digite nada.
         *
         *     **Sem token, e protegida pelo mesmo segredo que protege `nota.xml`:** o id
         *     opaco da sessão. Quem o tem é quem está na conversa. Exigir credencial aqui
         *     seria exigir login de um visitante anônimo para receber a própria nota.
         *
         *     **O assinante é filtrado por sessão no barramento**, por inclusão explícita:
         *     só chega o evento que carrega este `session_id`. Um evento sem sessão — a
         *     fila de aprovação, por exemplo — não vaza para cá por construção, e não por
         *     uma lista de proibidos que alguém esquece de atualizar.
         */
        get: operations["eventos_da_sessao_eventos_sessao__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operador/fila": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fila Do Operador
         * @description Os pedidos pagos esperando decisao (RF-3.2, REQ-2).
         *
         *     A fila e a consulta pelo **status do pedido**, nao pelo grafo: um pedido cuja
         *     pausa nao chegou a abrir continua aparecendo aqui, e a aprovacao conduz o
         *     grafo do comeco. Fila que depende de um `ainvoke` ter dado certo e fila que
         *     perde pedido em silencio.
         */
        get: operations["fila_do_operador_operador_fila_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operador/pedidos/{pedido_id}/aprovar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprovar A Nota
         * @description Aprova e retoma o grafo, que entao emite (RF-3.3, REQ-3).
         *
         *     Repare no que esta rota **nao** faz: ela nao emite. Ela grava a decisao e
         *     conduz o grafo; quem emite e `fiscal.emitir`, que rele a decisao do banco
         *     antes de agir. Parece um rodeio e e a garantia inteira — a autorizacao e o
         *     registro, nunca a chamada.
         */
        post: operations["aprovar_a_nota_operador_pedidos__pedido_id__aprovar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operador/pedidos/{pedido_id}/rejeitar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejeitar A Nota
         * @description Rejeita com motivo, e tira o pedido do caminho de emissao (RF-4.2).
         *
         *     O motivo nao e burocracia: ele e o que o cliente le no chat quando pergunta
         *     pela nota, por `consultar_pedido`. Uma rejeicao sem motivo vira silencio para
         *     quem pagou, e e o que o `golden-011` existe para nao deixar acontecer.
         */
        post: operations["rejeitar_a_nota_operador_pedidos__pedido_id__rejeitar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pagamento/mock/{pedido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pagina De Pagamento Falsa */
        get: operations["pagina_de_pagamento_falsa_pagamento_mock__pedido_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pagamento/mock/{pedido_id}/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar Pagamento Falso */
        post: operations["confirmar_pagamento_falso_pagamento_mock__pedido_id__confirmar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{pedido_id}/nota.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danfe Da Nota
         * @description A DANFE em PDF. `inline` para abrir no navegador, com nome ao salvar.
         */
        get: operations["danfe_da_nota_pedidos__pedido_id__nota_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{pedido_id}/nota.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Xml Da Nota
         * @description O XML da NF-e, para o contador da empresa compradora (RF-3.6, REQ-6).
         *
         *     **Aberta por link, e o link e o id opaco do pedido** — mesmo raciocinio do
         *     link de pagamento (S-04). Diferente da pagina do mock, este documento
         *     *carrega* dados do destinatario: e da natureza dele, e a alternativa seria
         *     autenticar o comprador, que e um sistema que este projeto ainda nao tem. O
         *     `uuid4` de `pedidos.novo_id` e o que sustenta a decisao, e ela esta escrita
         *     aqui em vez de escondida.
         */
        get: operations["xml_da_nota_pedidos__pedido_id__nota_xml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/pagamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook De Pagamento
         * @description A confirmação de pagamento. Zero IA neste caminho (RF-2.5, R8).
         *
         *     Três decisões, e cada uma existe por causa de uma falha concreta.
         *
         *     **Origem verificada antes de qualquer coisa.** Sem assinatura válida, 401 e
         *     nada acontece — inclusive quando o segredo não está configurado. O oposto
         *     transformaria uma variável de ambiente esquecida num endpoint aberto que
         *     muda o estado de um pedido pago.
         *
         *     **Quem afirma que foi pago é o gateway, não o POST.** A notificação diz
         *     *"olhe o pagamento 123"*; o servidor pergunta ao gateway o que aconteceu
         *     com ele e só então age. Confiar no corpo da requisição seria deixar o
         *     mensageiro decidir sobre dinheiro.
         *
         *     **Duplicata responde 200.** Ela é comportamento normal de gateway, não
         *     falha, e um 4xx faria o Mercado Pago reenviar para sempre o evento que já
         *     teve efeito. A idempotência de verdade está uma camada abaixo, na chave
         *     primária de `evento_de_pagamento` — não num `SELECT` antes do `INSERT`,
         *     que é a corrida que dois webhooks simultâneos ganham.
         */
        post: operations["webhook_de_pagamento_webhooks_pagamento_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AprovacaoPendente
         * @description Uma nota entrou na fila e espera decisão humana. É a notificação do HITL.
         *
         *     Deliberadamente magro: id, valor e razão social — o bastante para o sino tocar
         *     com contexto. O detalhe que autoriza a decisão continua vindo de
         *     `GET /operador/fila`, que é a projeção que o RF-3.2 governa. Um evento gordo
         *     seria uma segunda projeção da nota, e a que fica velha.
         */
        AprovacaoPendente: {
            /**
             * Em
             * Format: date-time
             */
            em: string;
            /** Pedido Id */
            pedido_id: string;
            /** Razao Social */
            razao_social: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "aprovacao_pendente";
            /** Total */
            total: number | string;
        };
        /**
         * AtrasoNoStream
         * @description Eventos foram descartados porque este assinante não os consumiu a tempo.
         *
         *     Existe para que a tela possa dizer *"você perdeu N atualizações, recarregando"*
         *     em vez de seguir exibindo um estado furado. É o preço da fila limitada, e a
         *     alternativa — bloquear quem publica — faria um painel lento segurar a resposta
         *     de um cliente.
         */
        AtrasoNoStream: {
            /**
             * Em
             * Format: date-time
             */
            em: string;
            /** Perdidos */
            perdidos: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "atraso";
        };
        /**
         * ChatRequest
         * @description One customer turn.
         */
        ChatRequest: {
            /**
             * Message
             * @description O que o cliente escreveu.
             */
            message: string;
            /**
             * Model
             * @description Modelo a usar, no formato `provedor:modelo`. Precisa estar entre os que `GET /models` devolve — texto livre aqui deixaria o cliente escolher para qual fornecedor o servidor autentica e quanto gasta (ADR-012).
             */
            model?: string | null;
            /**
             * Session Id
             * @description Identificador da conversa. Ausente na primeira mensagem: o servidor gera um e devolve no primeiro evento do stream.
             */
            session_id?: string | null;
        };
        /**
         * ComposicaoAvaliada
         * @description O veredito do validador, **como ele voltou** — nunca reprojetado.
         *
         *     É o evento que carrega a regra de ouro até a tela: o modelo propôs, o código
         *     respondeu isto, e o painel mostra a resposta do código. Reprojetar aqui seria
         *     dar ao painel a chance de discordar do validador.
         */
        ComposicaoAvaliada: {
            /**
             * Em
             * Format: date-time
             */
            em: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "composicao_avaliada";
            veredito: components["schemas"]["ComposicaoValidada"];
        };
        /**
         * ComposicaoDoPedido
         * @description Uma composição já validada pelo servidor, do jeito que ela é persistida.
         */
        ComposicaoDoPedido: {
            /** Itens */
            itens: components["schemas"]["ItemDoPedido"][];
            /** Orcamento Por Pessoa */
            orcamento_por_pessoa?: string | null;
            /** Pessoas */
            pessoas: number;
            /**
             * Restricoes
             * @default []
             */
            restricoes: ("lactose" | "gluten" | "ovos" | "castanhas" | "amendoim" | "alcool" | "acucar")[];
            tipo_de_evento: components["schemas"]["TipoDeEvento"];
            /** Total */
            total: string;
            /** Valor Por Pessoa */
            valor_por_pessoa: string;
        };
        /**
         * ComposicaoValidada
         * @description O veredito, do jeito que o modelo o lê.
         *
         *     Os nomes `total_composicao`, `valor_por_pessoa` e `problemas_composicao` são os
         *     que o corpus de `evals/` já usa em `fatos_ancorados` — o vocabulário do caso é de
         *     quem define a régua, e a tool se ajusta a ele, não o contrário.
         *
         *     `orcamento_por_pessoa` e `excedente_por_pessoa` voltam no retorno de propósito.
         *     São dinheiro, e todo valor em dinheiro que o modelo disser ao cliente tem que ter
         *     saído de uma tool: o teto e o estouro repetidos de memória seriam preço sem
         *     origem, mesmo quando certos (`groundedness._precos_divergentes`, RF-1.3).
         */
        ComposicaoValidada: {
            /** Aprovada */
            aprovada: boolean;
            /** Atende Pessoas */
            atende_pessoas: number;
            /**
             * Excedente Por Pessoa
             * @default null
             */
            excedente_por_pessoa: number | string | null;
            /** Itens */
            itens: components["schemas"]["ItemDaComposicao"][];
            /**
             * Orcamento Por Pessoa
             * @default null
             */
            orcamento_por_pessoa: number | string | null;
            /** Pessoas */
            pessoas: number;
            /**
             * Problemas Composicao
             * @default []
             */
            problemas_composicao: components["schemas"]["ProblemaDaComposicao"][];
            /** Tipo De Evento */
            tipo_de_evento: string;
            /** Total Composicao */
            total_composicao: number | string;
            /** Valor Por Pessoa */
            valor_por_pessoa: number | string;
        };
        /**
         * ConfigResponse
         * @description The configuration as the API is allowed to describe it. No secrets, ever.
         */
        ConfigResponse: {
            /**
             * Editable
             * @description Se este ambiente aceita gravar configuracao. Fora de APP_ENV=local e `false` ate existir autenticacao — a rota guarda credencial (S-02, D-8).
             */
            editable: boolean;
            /**
             * Encryption Ready
             * @description Se CONFIG_ENCRYPTION_KEY esta definida. Sem ela, gravar chave e recusado.
             */
            encryption_ready: boolean;
            /** Providers */
            providers: components["schemas"]["ProviderStatus"][];
            /** Selected Model */
            selected_model: string | null;
        };
        /**
         * ConfigUpdate
         * @description What the operator may change. Both fields optional, at least one required.
         */
        ConfigUpdate: {
            /**
             * Api Key
             * @description Credencial do provedor. Nunca volta em nenhuma resposta.
             */
            api_key?: string | null;
            /**
             * Model
             * @description Modelo default, `provedor:modelo`.
             */
            model?: string | null;
            /**
             * Provider
             * @description anthropic | openai
             */
            provider?: string | null;
        };
        /**
         * ConversaNaLista
         * @description Uma linha da lista de conversas.
         */
        ConversaNaLista: {
            /** Canal */
            canal: string;
            custo: components["schemas"]["CustoApurado"];
            /** Erros */
            erros: number;
            /**
             * Iniciada Em
             * Format: date-time
             */
            iniciada_em: string;
            /** Pedido Id */
            pedido_id?: string | null;
            /** Session Id */
            session_id: string;
            /** Status Do Pedido */
            status_do_pedido?: string | null;
            /** Turnos */
            turnos: number;
            /**
             * Ultima Atividade
             * Format: date-time
             */
            ultima_atividade: string;
        };
        /**
         * CustoApurado
         * @description O custo como a tela deve exibi-lo — inclusive quando não dá para saber.
         *
         *     `completo` é falso quando algum modelo não tem preço ou algum turno não
         *     informou consumo. A tela que ignora esse campo apresenta um parcial como total,
         *     que é o modo de falha que o ADR-015 nomeia.
         */
        CustoApurado: {
            /** Brl */
            brl?: string | null;
            /**
             * Completo
             * @default true
             */
            completo: boolean;
            /**
             * Modelos Sem Preco
             * @default []
             */
            modelos_sem_preco: string[];
            /**
             * Turnos Sem Uso
             * @default 0
             */
            turnos_sem_uso: number;
            /** Usd */
            usd?: string | null;
        };
        /**
         * DadosDoEvento
         * @description O `data` da notificação do Mercado Pago: o id do pagamento, e nada mais.
         */
        DadosDoEvento: {
            /** Id */
            id: string;
        };
        /**
         * DecisaoDoOperador
         * @description O corpo de aprovar e de rejeitar. Um contrato para as duas rotas.
         *
         *     `motivo` é opcional aqui e **obrigatório na rejeição** — quem impõe isso é
         *     `fiscal.Aprovacao`, não esta classe. Duas classes quase iguais fariam o cliente
         *     TypeScript da S-07 ter dois tipos para o mesmo formulário, e a regra continuaria
         *     valendo no servidor de qualquer jeito.
         */
        DecisaoDoOperador: {
            /**
             * Motivo
             * @description Obrigatório na rejeição — é o que o cliente recebe.
             */
            motivo?: string | null;
            /**
             * Operador
             * @description Quem está decidindo. Gravado como veio: este projeto ainda não tem autenticação, então é uma declaração, não uma identidade provada.
             */
            operador: string;
        };
        /**
         * DecisaoRegistrada
         * @description O que a rota responde depois de decidir — e o que **valeu**.
         *
         *     Pode não ser a decisão que acabou de chegar: a primeira vence (a chave primária
         *     de `aprovacao_de_nf`). Um segundo operador clicando em "aprovar" num pedido já
         *     rejeitado recebe de volta a rejeição, com quem e quando, em vez de um 200 que o
         *     faria acreditar que aprovou.
         */
        DecisaoRegistrada: {
            /** Chave Da Nota */
            chave_da_nota?: string | null;
            /**
             * Decidido Em
             * Format: date-time
             */
            decidido_em: string;
            /**
             * Decisao
             * @enum {string}
             */
            decisao: "aprovada" | "rejeitada";
            /** Motivo */
            motivo?: string | null;
            /**
             * Numero Nota
             * @description Preenchido quando a emissão já aconteceu.
             */
            numero_nota?: number | null;
            /** Operador */
            operador: string;
            /** Pedido Id */
            pedido_id: string;
        };
        /**
         * DestinatarioDaNota
         * @description O comprador PJ como o operador precisa vê-lo para conferir a nota.
         *
         *     **CNPJ em claro, e formatado.** É o oposto do que `mascarar_cnpj` faz no retorno
         *     de tool, e a diferença é o destinatário: lá o leitor é o modelo, e o número
         *     mascarado existe para não haver de onde copiá-lo para a resposta (ADR-007, R5).
         *     Aqui o leitor é a pessoa que vai autorizar a emissão, e conferir o documento **é
         *     o trabalho dela** — o `golden-011` rejeita uma nota justamente por um dado do
         *     destinatário. Uma fila com o CNPJ mascarado pediria uma decisão sobre um dado que
         *     ela não pode ler.
         */
        DestinatarioDaNota: {
            /**
             * Cnpj
             * @description Formatado, para conferência humana.
             */
            cnpj: string;
            /** Contato Email */
            contato_email: string;
            /** Contato Nome */
            contato_nome: string;
            endereco: components["schemas"]["Endereco"];
            /**
             * Inscricao Estadual
             * @description Como sairá na nota: a IE informada, ou ISENTO quando não houver.
             */
            inscricao_estadual: string;
            /** Razao Social */
            razao_social: string;
        };
        /**
         * DetalheDaConversa
         * @description A conversa inteira para a tela de rastreabilidade.
         */
        DetalheDaConversa: {
            /** Mensagens */
            mensagens: components["schemas"]["MensagemDaConversa"][];
            /**
             * Mensagens Indisponiveis
             * @description Verdadeiro quando o checkpointer não devolveu a conversa. A tela diz isso em vez de mostrar uma conversa vazia como se fosse curta.
             * @default false
             */
            mensagens_indisponiveis: boolean;
            resumo: components["schemas"]["ConversaNaLista"];
            /** Turnos */
            turnos: components["schemas"]["TurnoDoPainel"][];
            /** Uso */
            uso: components["schemas"]["UsoPorModelo"][];
            /** Vereditos */
            vereditos: components["schemas"]["VeredictoNoPainel"][];
        };
        /**
         * DoneEvent
         * @description End of stream. A client that never sees this one is still waiting.
         */
        DoneEvent: {
            /** Session Id */
            session_id: string;
        };
        /**
         * Endereco
         * @description Onde a entrega chega — e o que a DANFE modelo 55 exige do destinatário.
         *
         *     O B2C não coletava endereço, e o ADR-013 registra isso como furo que o pivô
         *     fechou: nota de destinatário PJ sem endereço não é nota fiel, é nota no que dava.
         */
        Endereco: {
            /** Bairro */
            bairro: string;
            /** Cep */
            cep: string;
            /** Cidade */
            cidade: string;
            /** Complemento */
            complemento?: string | null;
            /** Logradouro */
            logradouro: string;
            /** Numero */
            numero: string;
            /** Uf */
            uf: string;
        };
        /**
         * ErrorEvent
         * @description Something failed mid-stream, after the HTTP status was already sent as 200.
         */
        ErrorEvent: {
            /** Detail */
            detail: string;
        };
        /**
         * EventosDoChat
         * @description Reúne os quatro eventos de `/chat` para que entrem no schema.
         *
         *     Não é um corpo que alguma rota devolva: é o veículo que leva os quatro modelos
         *     até `components.schemas`. Está declarado como classe, e não montado à mão em
         *     dicionário, para que ele não possa divergir dos modelos que a rota realmente
         *     emite — se alguém acrescentar um campo em `TokenEvent`, este schema acompanha.
         */
        EventosDoChat: {
            done: components["schemas"]["DoneEvent"];
            error: components["schemas"]["ErrorEvent"];
            session: components["schemas"]["SessionEvent"];
            token: components["schemas"]["TokenEvent"];
        };
        /**
         * FilaDoOperador
         * @description A fila inteira, do mais antigo para o mais novo.
         */
        FilaDoOperador: {
            /** Pendentes */
            pendentes: components["schemas"]["PedidoNaFila"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * ItemDaComposicao
         * @description Uma linha da composição, com a quantidade que o código derivou.
         */
        ItemDaComposicao: {
            /** Nome */
            nome: string;
            /** Preco Unitario */
            preco_unitario: number | string;
            /** Produto Id */
            produto_id: string;
            /** Quantidade */
            quantidade: number;
            /** Rendimento */
            rendimento: number;
            /** Subtotal */
            subtotal: number | string;
            /** Tipo */
            tipo: string;
        };
        /**
         * ItemDoPedido
         * @description Uma linha, congelada no preço que valia quando o pedido foi criado.
         */
        ItemDoPedido: {
            /** Nome */
            nome: string;
            /** Preco Unitario */
            preco_unitario: string;
            /** Produto Id */
            produto_id: string;
            /** Quantidade */
            quantidade: number;
            /** Rendimento */
            rendimento: number;
            /** Subtotal */
            subtotal: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "queijo" | "cafe" | "doce" | "cachaca" | "licor" | "petisco";
        };
        /**
         * MensagemDaConversa
         * @description Uma fala da conversa, lida do checkpointer — não de uma cópia nossa.
         *
         *     `ferramenta` e `argumentos` existem para a tela de rastreabilidade: é ali que se
         *     vê **o que o modelo propôs** ao lado do que o código respondeu. Sem os
         *     argumentos, a proposta do modelo some e sobra só o veredito.
         */
        MensagemDaConversa: {
            /** Argumentos */
            argumentos?: string | null;
            /** Ferramenta */
            ferramenta?: string | null;
            /**
             * Papel
             * @enum {string}
             */
            papel: "cliente" | "atendente" | "ferramenta";
            /** Texto */
            texto: string;
        };
        /**
         * MensagemRegistrada
         * @description Uma fala completa, do cliente ou do atendente.
         *
         *     O painel recebe a fala do atendente **inteira**, no fim do turno, e não token a
         *     token como o cliente. O cliente espera a frase se formar porque é a conversa
         *     dele; o operador está olhando uma lista de conversas, e streaming em todas ao
         *     mesmo tempo é ruído que nenhuma decisão usa.
         */
        MensagemRegistrada: {
            /**
             * Em
             * Format: date-time
             */
            em: string;
            /**
             * Papel
             * @enum {string}
             */
            papel: "cliente" | "atendente";
            /** Session Id */
            session_id: string;
            /** Texto */
            texto: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "mensagem";
        };
        /**
         * Metricas
         * @description Os KPIs da janela. Cada número já somado, e cada ausência explícita.
         */
        Metricas: {
            /** Aprovadas */
            aprovadas: number;
            /** Atendimento Medio Ms */
            atendimento_medio_ms?: number | null;
            /** Conversas */
            conversas: number;
            /** Conversas Com Pedido */
            conversas_com_pedido: number;
            /**
             * @default {
             *       "completo": true,
             *       "modelos_sem_preco": [],
             *       "turnos_sem_uso": 0
             *     }
             */
            custo: components["schemas"]["CustoApurado"];
            /**
             * Custo Sobre Ticket
             * @description Custo de LLM como fração da receita. `None` sem cotação do dólar configurada — comparar dólar com real por uma taxa inventada seria pior que não comparar.
             */
            custo_sobre_ticket?: string | null;
            /** Decisoes */
            decisoes: number;
            /**
             * Desde
             * Format: date-time
             */
            desde: string;
            /** Erros De Stream */
            erros_de_stream: number;
            /** Fila Pendentes */
            fila_pendentes: number;
            /** Janela */
            janela: string;
            /** Pedidos */
            pedidos: number;
            /**
             * Primeiro Token Alvo Ms
             * @description RNF-4. Vai no contrato para a régua aparecer na tela.
             * @default 3000
             */
            primeiro_token_alvo_ms: number;
            /** Primeiro Token P50 Ms */
            primeiro_token_p50_ms?: number | null;
            /** Primeiro Token P95 Ms */
            primeiro_token_p95_ms?: number | null;
            /** Receita */
            receita: string;
            /**
             * Recusas Do Validador
             * @default []
             */
            recusas_do_validador: components["schemas"]["RecusaDoValidador"][];
            /** Taxa De Aprovacao */
            taxa_de_aprovacao?: string | null;
            /** Taxa De Conversao */
            taxa_de_conversao?: string | null;
            /** Ticket Medio */
            ticket_medio?: string | null;
            /** Turnos */
            turnos: number;
            /** Turnos Por Conversa */
            turnos_por_conversa?: string | null;
            /**
             * Uso
             * @default []
             */
            uso: components["schemas"]["UsoPorModelo"][];
        };
        /**
         * ModelsResponse
         * @description What the picker in the UI is offered — read from the providers, not from memory.
         */
        ModelsResponse: {
            /** Models */
            models: string[];
            /** Selected */
            selected: string | null;
        };
        /**
         * NotaDecidida
         * @description A decisão saiu. Com `session_id`, é o que faz o cartão da NF aparecer no chat.
         */
        NotaDecidida: {
            /**
             * Decisao
             * @enum {string}
             */
            decisao: "aprovada" | "rejeitada";
            /**
             * Em
             * Format: date-time
             */
            em: string;
            /**
             * Motivo
             * @default null
             */
            motivo: string | null;
            /**
             * Numero Nota
             * @default null
             */
            numero_nota: number | null;
            /** Pedido Id */
            pedido_id: string;
            /**
             * Session Id
             * @default null
             */
            session_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "nota_decidida";
        };
        /**
         * NotificacaoDePagamento
         * @description O corpo do webhook do Mercado Pago (S-04, RF-2.5).
         *
         *     `extra="ignore"` de propósito: o gateway acrescenta campos com o tempo, e uma
         *     notificação recusada por um campo novo é um pagamento que fica sem efeito por
         *     um motivo que nada tem a ver com dinheiro. O que precisa estar presente está
         *     tipado; o resto passa.
         */
        NotificacaoDePagamento: {
            /** Action */
            action?: string | null;
            data: components["schemas"]["DadosDoEvento"];
            /**
             * Type
             * @description `payment` é o que nos interessa.
             */
            type?: string | null;
        };
        /** PaginaDeConversas */
        PaginaDeConversas: {
            /** Conversas */
            conversas: components["schemas"]["ConversaNaLista"][];
        };
        /** PaginaDePedidos */
        PaginaDePedidos: {
            /** Pedidos */
            pedidos: components["schemas"]["PedidoNoPainel"][];
        };
        /**
         * PedidoAtualizado
         * @description O pedido mudou de estado. `session_id` é o que permite avisar o cliente.
         */
        PedidoAtualizado: {
            /**
             * Em
             * Format: date-time
             */
            em: string;
            /** Pedido Id */
            pedido_id: string;
            /** Razao Social */
            razao_social: string;
            /**
             * Session Id
             * @default null
             */
            session_id: string | null;
            /** Status */
            status: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "pedido_atualizado";
            /** Total */
            total: number | string;
            /**
             * Url Pagamento
             * @description O link do gateway, quando já existe. Vai no evento porque a REQ-8 pede o link RENDERIZADO no widget, e um link que só existe no meio da frase do atendente obriga o cliente a caçá-lo no histórico.
             * @default null
             */
            url_pagamento: string | null;
        };
        /**
         * PedidoNaFila
         * @description Um pedido esperando decisão, com os dados completos da nota (RF-3.2).
         *
         *     `composicoes` são os **modelos persistidos**, reusados e não reprojetados. É
         *     deliberado: o operador precisa ver item a item exatamente o que a nota vai ler,
         *     e uma segunda projeção do mesmo dado é a que fica velha — aprovando-se então uma
         *     coisa e emitindo-se outra.
         */
        PedidoNaFila: {
            /** Composicoes */
            composicoes: components["schemas"]["ComposicaoDoPedido"][];
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            destinatario: components["schemas"]["DestinatarioDaNota"];
            /** Pedido Id */
            pedido_id: string;
            /** Total */
            total: string;
        };
        /**
         * PedidoNoPainel
         * @description Um pedido como a tela de pedidos o lista e detalha.
         */
        PedidoNoPainel: {
            /** Cnpj */
            cnpj: string;
            /**
             * Composicoes
             * @default []
             */
            composicoes: components["schemas"]["ComposicaoDoPedido"][];
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Numero Nota */
            numero_nota?: number | null;
            /** Pedido Id */
            pedido_id: string;
            /** Razao Social */
            razao_social: string;
            /** Status */
            status: string;
            /** Status Nf */
            status_nf: string;
            /** Total */
            total: string;
            /** Url Danfe */
            url_danfe?: string | null;
            /** Url Pagamento */
            url_pagamento?: string | null;
            /** Url Xml */
            url_xml?: string | null;
        };
        /**
         * ProblemaDaComposicao
         * @description Um motivo de recusa, com o `motivo` tipado ao lado da frase.
         *
         *     O motivo separado da mensagem é o que deixa `golden-014` ser verificável: uma
         *     reprovação por slot precisa ser distinguível de uma reprovação por preço sem que
         *     alguém tenha que interpretar o texto.
         */
        ProblemaDaComposicao: {
            /** Mensagem */
            mensagem: string;
            /** Motivo */
            motivo: string;
            /**
             * Produto Id
             * @default null
             */
            produto_id: string | null;
        };
        /**
         * PromptVigente
         * @description Um prompt do agente, em modo leitura. Nunca editável — ADR-015.
         *
         *     `sha` é do texto, não do arquivo: é o que permite conferir numa demo que o
         *     prompt em memória é o do commit, sem abrir o repositório.
         */
        PromptVigente: {
            /** Arquivo */
            arquivo: string;
            /**
             * Ferramentas
             * @default []
             */
            ferramentas: string[];
            /** Sha */
            sha: string;
            /** Subagent */
            subagent: string;
            /** Texto */
            texto: string;
        };
        /** PromptsDoAgente */
        PromptsDoAgente: {
            /**
             * Editavel
             * @description Sempre falso, em todo ambiente. Prompt muda por PR com evals — editá-lo em runtime contornaria o portão do ADR-014 (ADR-015).
             * @default false
             * @constant
             */
            editavel: false;
            /** Prompts */
            prompts: components["schemas"]["PromptVigente"][];
            /** Tabela De Precos Atualizada Em */
            tabela_de_precos_atualizada_em?: string | null;
        };
        /**
         * ProviderStatus
         * @description Whether a provider can be used — and never how.
         *
         *     `hint` is the last four characters of the key. Enough for a person to recognise
         *     which credential is in place, useless to anyone who wants to spend it.
         */
        ProviderStatus: {
            /** Configured */
            configured: boolean;
            /** Hint */
            hint?: string | null;
            /** Provider */
            provider: string;
            /**
             * Source
             * @enum {string}
             */
            source: "banco" | "ambiente" | "nenhuma";
        };
        /** RecusaDoValidador */
        RecusaDoValidador: {
            /** Motivo */
            motivo: string;
            /** Recusas */
            recusas: number;
        };
        /**
         * SessaoIniciada
         * @description Uma conversa nova apareceu. É o que faz a linha surgir na lista do painel.
         */
        SessaoIniciada: {
            /** Canal */
            canal: string;
            /**
             * Em
             * Format: date-time
             */
            em: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "sessao_iniciada";
        };
        /**
         * SessionEvent
         * @description First event of every stream, so the client can continue the conversation.
         */
        SessionEvent: {
            /** Session Id */
            session_id: string;
        };
        /**
         * TipoDeEvento
         * @description Os quatro eventos que a Vendinha monta (ADR-013).
         * @enum {string}
         */
        TipoDeEvento: "cafe_da_manha" | "happy_hour" | "cesta_de_fim_de_ano" | "kit_boas_vindas";
        /**
         * TokenEvent
         * @description One chunk of the answer.
         *
         *     JSON-encoded rather than raw text on the SSE `data:` line: a token that happens
         *     to contain a newline would otherwise be split across two events and silently
         *     change the message.
         */
        TokenEvent: {
            /** Text */
            text: string;
        };
        /**
         * TurnoDoPainel
         * @description Um turno com o que ele custou e quanto o cliente esperou.
         */
        TurnoDoPainel: {
            custo: components["schemas"]["CustoApurado"];
            /** Duracao Ms */
            duracao_ms: number;
            /** Erro */
            erro: boolean;
            /**
             * Iniciado Em
             * Format: date-time
             */
            iniciado_em: string;
            /** Modelo */
            modelo: string;
            /** Primeiro Token Ms */
            primeiro_token_ms?: number | null;
            /** Tokens Entrada */
            tokens_entrada?: number | null;
            /** Tokens Saida */
            tokens_saida?: number | null;
        };
        /** UsoPorModelo */
        UsoPorModelo: {
            /** Modelo */
            modelo: string;
            /** Tokens Entrada */
            tokens_entrada: number;
            /** Tokens Saida */
            tokens_saida: number;
            /** Turnos */
            turnos: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VeredictoNoPainel
         * @description Uma passagem pelo validador, como ele a devolveu.
         */
        VeredictoNoPainel: {
            /** Aprovada */
            aprovada: boolean;
            /**
             * Avaliado Em
             * Format: date-time
             */
            avaliado_em: string;
            /**
             * Motivos
             * @default []
             */
            motivos: string[];
            /** Pessoas */
            pessoas: number;
            /** Tipo De Evento */
            tipo_de_evento: string;
            /** Total */
            total: string;
            /** Valor Por Pessoa */
            valor_por_pessoa: string;
        };
        /**
         * WebhookProcessado
         * @description O que a rota responde. Sempre 200 quando a origem confere.
         *
         *     `resultado` distingue o que aconteceu sem transformar duplicata em erro: um
         *     gateway que recebe 4xx ou 5xx reenvia o evento, e reenviar é justamente o que
         *     a idempotência existe para tolerar.
         */
        WebhookProcessado: {
            /**
             * Resultado
             * @enum {string}
             */
            resultado: "registrado" | "duplicado" | "ignorado";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    conversas_admin_conversas_get: {
        parameters: {
            query?: {
                limite?: number;
                offset?: number;
            };
            header?: {
                "x-operador-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeConversas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversa_admin_conversas__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-operador-token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalheDaConversa"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eventos_do_painel_admin_eventos_get: {
        parameters: {
            query?: never;
            header?: {
                "x-operador-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tudo que acontece no servidor, para o painel. O nome do `event:` é o campo `tipo`. Um `atraso` significa que este assinante perdeu eventos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SessaoIniciada"] | components["schemas"]["MensagemRegistrada"] | components["schemas"]["ComposicaoAvaliada"] | components["schemas"]["PedidoAtualizado"] | components["schemas"]["AprovacaoPendente"] | components["schemas"]["NotaDecidida"] | components["schemas"]["AtrasoNoStream"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metricas_admin_metricas_get: {
        parameters: {
            query?: {
                janela?: string;
            };
            header?: {
                "x-operador-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metricas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lista_de_pedidos_admin_pedidos_get: {
        parameters: {
            query?: {
                limite?: number;
                offset?: number;
            };
            header?: {
                "x-operador-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDePedidos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pedido_no_painel_admin_pedidos__pedido_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-operador-token"?: string | null;
            };
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoNoPainel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prompts_admin_prompts_get: {
        parameters: {
            query?: never;
            header?: {
                "x-operador-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptsDoAgente"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Stream do atendimento: `session` primeiro, `token` a cada pedaço da resposta, `error` quando falha depois do primeiro byte, e `done` sempre. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["EventosDoChat"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    write_config_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eventos_da_sessao_eventos_sessao__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Só os eventos desta conversa — o barramento filtra por `session_id`. É o que faz a NF aparecer no chat sem o cliente perguntar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SessaoIniciada"] | components["schemas"]["MensagemRegistrada"] | components["schemas"]["ComposicaoAvaliada"] | components["schemas"]["PedidoAtualizado"] | components["schemas"]["AprovacaoPendente"] | components["schemas"]["NotaDecidida"] | components["schemas"]["AtrasoNoStream"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    fila_do_operador_operador_fila_get: {
        parameters: {
            query?: never;
            header?: {
                "x-operador-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaDoOperador"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aprovar_a_nota_operador_pedidos__pedido_id__aprovar_post: {
        parameters: {
            query?: never;
            header?: {
                "x-operador-token"?: string | null;
            };
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisaoDoOperador"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisaoRegistrada"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rejeitar_a_nota_operador_pedidos__pedido_id__rejeitar_post: {
        parameters: {
            query?: never;
            header?: {
                "x-operador-token"?: string | null;
            };
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisaoDoOperador"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisaoRegistrada"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pagina_de_pagamento_falsa_pagamento_mock__pedido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmar_pagamento_falso_pagamento_mock__pedido_id__confirmar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookProcessado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    danfe_da_nota_pedidos__pedido_id__nota_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    xml_da_nota_pedidos__pedido_id__nota_xml_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_de_pagamento_webhooks_pagamento_post: {
        parameters: {
            query?: never;
            header?: {
                "x-signature"?: string | null;
                "x-request-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificacaoDePagamento"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookProcessado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
