"""The HTTP surface: one chat endpoint that streams, and a health check.

Two decisions worth stating, because both are the kind that read as detail and
behave as architecture.

**The session id is generated by the server and announced first.** A client that
has to invent its own id will eventually invent a colliding one, and a stream that
announces the id only at the end forces the client to buffer before it can
continue the conversation. So the first event on every stream is the id — new or
echoed back — and it is the same string the checkpointer uses as `thread_id`.

**Errors after the first byte are events, not status codes.** Once the response
starts streaming the status line is already 200; a failure at token forty cannot
retroactively become a 500. It arrives as an `error` event, which is a thing the
client can actually render.
"""

import logging
import uuid
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, Request
from langchain_core.messages import HumanMessage
from langfuse import propagate_attributes
from sse_starlette.sse import EventSourceResponse

from vendinha.config import get_settings
from vendinha.db import open_checkpointer
from vendinha.graph import build_graph, session_config
from vendinha.observability import callback_handler, install_log_redaction
from vendinha.providers import resolve_model
from vendinha.schemas import (
    ChatRequest,
    DoneEvent,
    ErrorEvent,
    HealthResponse,
    SessionEvent,
    TokenEvent,
)

logger = logging.getLogger(__name__)


def create_app(graph: Any | None = None) -> FastAPI:
    """Build the application.

    `graph` exists for the tests, and it is injected at a seam the architecture
    already declares: the model behind it is a `BaseChatModel` (ADR-012) and the
    checkpointer is a LangGraph interface with more than one implementation. When
    it is `None` — the production path — the lifespan opens Postgres and builds the
    real thing from configuration.
    """

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        # After uvicorn has configured logging, never before: the filter attaches to
        # the root handlers, and there are none until the server sets them up.
        install_log_redaction()
        app.state.langfuse = callback_handler()

        if graph is not None:
            app.state.graph = graph
            yield
            return

        settings = get_settings()
        async with open_checkpointer(settings.database_url) as checkpointer:
            app.state.graph = build_graph(resolve_model(settings.llm_model), checkpointer)
            yield

    app = FastAPI(
        title="Vendinha",
        description="Agente de vendas do empório mineiro digital.",
        version="0.1.0",
        lifespan=lifespan,
    )

    @app.get("/health", response_model=HealthResponse)
    async def health() -> HealthResponse:
        return HealthResponse(status="ok")

    @app.post("/chat")
    async def chat(payload: ChatRequest, request: Request) -> EventSourceResponse:
        session_id = payload.session_id or uuid.uuid4().hex
        graph = request.app.state.graph

        handler = getattr(request.app.state, "langfuse", None)
        config = session_config(session_id)
        if handler is not None:
            config = {**config, "callbacks": [handler]}

        async def stream() -> AsyncIterator[dict[str, str]]:
            yield {
                "event": "session",
                "data": SessionEvent(session_id=session_id).model_dump_json(),
            }
            try:
                # `propagate_attributes` is what makes every observation under this
                # turn carry the session id, so the trace is findable by the same
                # string the customer's client holds — and the same one the
                # checkpointer uses as thread_id.
                with propagate_attributes(session_id=session_id, trace_name="conversa"):
                    async for chunk, _ in graph.astream(
                        {
                            "session_id": session_id,
                            "messages": [HumanMessage(content=payload.message)],
                        },
                        config=config,
                        stream_mode="messages",
                    ):
                        # `.text` flattens content blocks: a provider answering
                        # with a list of typed blocks and one answering with a
                        # plain string have to look the same to the client.
                        if chunk.text:
                            yield {
                                "event": "token",
                                "data": TokenEvent(text=chunk.text).model_dump_json(),
                            }
            except Exception:
                # Loud on our side, vague on the customer's. The exception carries
                # DSNs, model names and limits; `adversarial-006` fails a run that
                # leaks internal configuration or tool names into an answer.
                logger.exception("failed to generate an answer for session %s", session_id)
                yield {
                    "event": "error",
                    "data": ErrorEvent(
                        detail="não consegui responder agora. pode tentar de novo?"
                    ).model_dump_json(),
                }

            # Outside the try, and never inside a `finally`: yielding while an
            # exception propagates out of an async generator is how a stream ends
            # with "generator ignored GeneratorExit" instead of with `done`.
            yield {
                "event": "done",
                "data": DoneEvent(session_id=session_id).model_dump_json(),
            }

        return EventSourceResponse(stream())

    return app


app = create_app()
